config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  devise_for :users

  get '/Admin' => 'user#admin_login'
  get '/logout' => 'user#logout'

  get 'cart/index'
  get '/cart' => 'cart#index' 
  get '/cart/:id' => 'cart#add'
  get '/cart/clear' => 'cart#clearCart' 

  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  resources :profiles
  resources :orders
  resources :items
  resources :designers
  resources :publishers
  resources :addresses

end

app/models/designer.rb
class Designer < ActiveRecord::Base
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  before_filter :ensure_admin, :only => [:edit, :update, :destroy]
  before_action :set_designer, only: [:show, :edit, :update, :destroy]

  # GET /designers
  # GET /designers.json
  def index
    @designers = Designer.all
  end

  # GET /designers/1
  # GET /designers/1.json
  def show
  end

  # GET /designers/new
  def new
    @designer = Designer.new
  end

  # GET /designers/1/edit
  def edit
  end

  # POST /designers
  # POST /designers.json
  def create
    @designer = Designer.new(designer_params)

    respond_to do |format|
      if @designer.save
        format.html { redirect_to @designer, notice: 'Designer was successfully created.' }
        format.json { render :show, status: :created, location: @designer }
      else
        format.html { render :new }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designers/1
  # PATCH/PUT /designers/1.json
  def update
    respond_to do |format|
      if @designer.update(designer_params)
        format.html { redirect_to @designer, notice: 'Designer was successfully updated.' }
        format.json { render :show, status: :ok, location: @designer }
      else
        format.html { render :edit }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designers/1
  # DELETE /designers/1.json
  def destroy
    @designer.destroy
    respond_to do |format|
      format.html { redirect_to designers_url, notice: 'Designer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designer
      @designer = Designer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designer_params
      params.require(:designer).permit(:name, :website)
    end
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/views/designers/_form.html.erb
<%= form_for(@designer) do |f| %>
  <% if @designer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@designer.errors.count, "error") %> prohibited this designer from being saved:</h2>

      <ul>
      <% @designer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designers/edit.html.erb
<h1>Editing Designer</h1>

<%= render 'form' %>

<%= link_to 'Show', @designer %> |
<%= link_to 'Back', designers_path %>

app/views/designers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Designers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designers.each do |designer| %>
      <tr>
        <td><%= designer.name %></td>
        <td><%= designer.website %></td>
        <td colspan="3">
          <% if current_user.try(:admin?) %>
            <%= link_to 'Show', designer %>
            <%= link_to 'Edit', edit_designer_path(designer) %>
            <%= link_to 'Destroy', designer, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.try(:admin?) %>
  <%= link_to 'New Designer', new_designer_path %>
<% end %>

app/views/designers/new.html.erb
<h1>New Designer</h1>

<%= render 'form' %>

<%= link_to 'Back', designers_path %>

app/views/designers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @designer.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @designer.website %>
</p>

<% if current_user.try(:admin?) %>
  <%= link_to 'Edit', edit_designer_path(@designer) %> |
  <%= link_to 'Back', designers_path %>
<% end %>